setwd("~/Dropbox/training_courses/R/HarvardX_PH125.5x_ProductivityTools/murder")
library( tidyverse )
murders <- read.csv( 'data/murders.csv' )
murders <- murders %>% mutate( region = factor( region ), rate = total / population * 10^5 )
save( murders, file = 'rdas/murders.rda' )
